### PR TITLE
Update compat bounds in Project.toml

### PR DESCRIPTION
**Pull request by eschnett**
Allow newer dependencies of some packages.

### CODE REVIEW

**Comment by Klafyvel** [comment]
Would it be possible to merge this PR? locking Interpolations.jl to an outdated version is a bit annoying :(

**Comment by simonschoelly** [comment]
Sorry for the delay, merging it now.

**Comment by simonschoelly** [comment]
Thank you!

I published a new `v0.3.3` release.

**Comment by Klafyvel** [comment]
Thank you for merging this. :)

**Pull request merged**
